ver 1 (using standard functions, without recursion)
der-HANS/study pull request #1
Opened 2021-11-18 09:31 UTC by der-HANS

2021-11-18 15:24 UTC, moklidia requested changes

2021-11-18 15:24 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +        search(arr, qry, idx_start, idx_end)
Перепиши, пожалуйста, не сокращая названия переменных. Очень сложно читать.

2021-11-18 15:24 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +        end
Попробуй найти максимальное число через редьюс

2021-11-18 15:24 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +        end
Нужно сделать через map

2021-11-18 23:33 UTC, der-HANS commented on test/exercise/arrays/solution.rb
> +        search(arr, qry, idx_start, idx_end)
Наименования переменных поправил. (v 3)

2021-11-18 23:50 UTC, der-HANS commented on test/exercise/arrays/solution.rb
> +        end
Поиск максимального числа осуществил c использованием reduce (ver 4)

2021-11-19 00:01 UTC, der-HANS commented on test/exercise/arrays/solution.rb
> +        end
Поправил. (ver 5)
Прошу обратить внимание, что фактически мы вернулись в ver 1.

2021-11-19 11:36 UTC, moklidia approved these changes

2021-11-19 23:48 UTC, merged