Solving problems fp
der-HANS/study pull request #2
Opened 2021-11-18 12:46 UTC by der-HANS

2021-11-19 11:33 UTC, moklidia requested changes

2021-11-19 11:33 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        arr = _array.reject { |film| film['rating_kinopoisk'].to_f.zero? || !film['country']&.include?(',') }.map { |film| film['rating_kinopoisk'].to_f }
Нижнее подчеркивание _ ставится перед неиспользуемыми переменными, а ты используешь array в теле функции

2021-11-19 11:33 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        _films.reject { |f| f['rating_kinopoisk'].to_f < _threshold }.map { |f| f['name'] }.join.count 'и'
То же самое

2021-11-20 00:41 UTC, der-HANS commented on test/exercise/fp/solution.rb
> +        arr = _array.reject { |film| film['rating_kinopoisk'].to_f.zero? || !film['country']&.include?(',') }.map { |film| film['rating_kinopoisk'].to_f }
Переименовал переменные (ver 3)

2021-11-20 00:41 UTC, der-HANS commented on test/exercise/fp/solution.rb
> +        _films.reject { |f| f['rating_kinopoisk'].to_f < _threshold }.map { |f| f['name'] }.join.count 'и'
Переименовал переменные (ver 3)

2021-11-22 12:13 UTC, Andrew8xx8 approved these changes

2021-11-22 16:37 UTC, merged