Solving problems fp2
der-HANS/study pull request #3
Opened 2021-11-18 12:51 UTC by der-HANS

2021-11-19 11:12 UTC, moklidia requested changes

2021-11-19 11:12 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +          value = !block_given? ? item : yield(item)
Во-первых в компакт обычно не передают блок, во-вторых, если используешь тернарный оператор старайся избегать банга (!) - он усложняет читаемость.

2021-11-19 11:12 UTC, moklidia commented on test/exercise/fp2/solution.rb
> +        @new_ary = Exercise::Fp2::MyArray.new
@new_ary - непонятное сокращение
Попробуй просто MyArray.new или  self.new

2021-11-20 11:29 UTC, der-HANS commented on test/exercise/fp2/solution.rb
> +          value = !block_given? ? item : yield(item)
Убрал обработку блока из compact. 
Убрал проверку с бангом. (version 2)

2021-11-20 11:30 UTC, der-HANS commented on test/exercise/fp2/solution.rb
> +        @new_ary = Exercise::Fp2::MyArray.new
Замена наименования переменной @new_ary => @out_ary (version 2)

2021-11-22 12:16 UTC, Andrew8xx8 requested changes

2021-11-22 12:16 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        @out_ary = Exercise::Fp2::MyArray.new
Аналогично, `compact` нужно реализовать через `reduce`

2021-11-22 12:16 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        @out_ary = Exercise::Fp2::MyArray.new
Это не ФП. `map` нужно реализовать через `reduce`, а в данном случае нарушается принцип иммутабельности (изменяется out_array) и чистой функции (out_array является глобальной переменной для блока в 36 строке.

2021-11-22 12:16 UTC, Andrew8xx8 commented on test/exercise/fp2/solution.rb
> +        acc ||= items.delete_at(0)
Зачем dup и delete_at использовать? Должно работать без этого, в примере с each выше правильно сделано.

2021-11-24 01:10 UTC, der-HANS commented on test/exercise/fp2/solution.rb
> +        acc ||= items.delete_at(0)
Все недочеты устранил (Solving problems fp2 [v3])

2021-11-24 11:46 UTC, merged